/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
/**
 *
 * @author MOKLET-1
 */
public class transaksi extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    Connection cn = koneksi.Koneksidb.BukaKoneksi();
    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        Connection cn1 = cn;
        refreshCombo();
        refreshTabel();
    }
    
    class penjualan extends transaksi{
        int id_transaksi, id_produk, harga, qty, total_bayar;
        String nama_pelanggan, tanggal, nama_produk;
        public penjualan() {
            this.nama_pelanggan = fnama_pelanggan.getText();
            String combo = fid_produk.getSelectedItem().toString();
            String[] arr = combo.split(":");
            this.id_produk = Integer.parseInt(arr[0]);
            try {
                Date date = ftanggal.getDate();
                DateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
                this.tanggal = dateformat.format(date);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            this.nama_produk = arr[1];
            this.harga = Integer.parseInt(arr[2]);
            this.qty = Integer.parseInt(fqty.getText());
            this.total_bayar = this.harga * this.qty;
        }
    }
    
    public void refreshTabel(){
        model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Nama Pelanggan");
        model.addColumn("ID Produk");
        model.addColumn("Tanggal");
        model.addColumn("Nama Produk");
        model.addColumn("Harga");
        model.addColumn("Qty");
        model.addColumn("Total Bayar");
        ttransaksi.setModel(model);
        try {
            this.stat = cn.prepareStatement("select * from transaksi");
            this.rs = this.stat.executeQuery();
            while (rs.next()){
                Object[] data={
                  rs.getString(1),
                  rs.getString(2),
                  rs.getString(3),
                  rs.getString(4),
                  rs.getString(5),
                  rs.getString(6),
                  rs.getString(7),
                  rs.getString(8)
                };
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        fid_transaksi.setText("");
        fnama_pelanggan.setText("");
        fqty.setText("");
        ftotal.setText("");
        
    }
    
    public void refreshCombo(){
        try {
            this.stat = cn.prepareStatement("select * from produk");
            this.rs = this.stat.executeQuery();
             while (rs.next()){
                 fid_produk.addItem(rs.getString("id_produk")+":"+rs.getString("nama_produk")+":"+rs.getString("harga"));
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        ttransaksi = new javax.swing.JTable();
        binput = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fnama_pelanggan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fqty = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ftanggal = new com.toedter.calendar.JDateChooser();
        fid_produk = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ftotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fid_transaksi = new javax.swing.JTextField();
        bproduk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ttransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ttransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttransaksiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ttransaksi);

        binput.setText("Input");
        binput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binputActionPerformed(evt);
            }
        });

        bupdate.setText("Update");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });

        bdelete.setText("Delete");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });

        jLabel4.setText("Tanggal :");

        jLabel3.setText("id_produk : ");

        jLabel2.setText("Nama pelanggan :");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Transaksi");

        jLabel5.setText("Qty :");

        fid_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fid_produkActionPerformed(evt);
            }
        });

        jLabel6.setText("Total :");

        ftotal.setEditable(false);
        ftotal.setEnabled(false);

        jLabel8.setText("id_transaksi");

        fid_transaksi.setEditable(false);
        fid_transaksi.setEnabled(false);
        fid_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fid_transaksiActionPerformed(evt);
            }
        });

        bproduk.setText("Produk");
        bproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprodukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bproduk)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fid_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fnama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fid_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(67, 67, 67)
                                            .addComponent(ftanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ftotal, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(fqty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(binput)
                        .addGap(18, 18, 18)
                        .addComponent(bupdate)
                        .addGap(18, 18, 18)
                        .addComponent(bdelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bproduk)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fid_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fnama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fid_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fqty, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ftanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdelete)
                    .addComponent(bupdate)
                    .addComponent(binput))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        try {
             penjualan tran = new penjualan();
             tran.id_transaksi = Integer.parseInt(fid_transaksi.getText());
             this.stat = cn.prepareStatement("update transaksi set nama_pelanggan=?,"+ "id_produk=?,tanggal=?,nama_produk=?,harga=?,"
                     + "qty=?,total_bayar=? where id_transaksi=?");
             this.stat.setString(1, tran.nama_pelanggan);
             this.stat.setInt(2, tran.id_produk);
             this.stat.setString(3, tran.tanggal);
             this.stat.setString(4, tran.nama_produk);
             this.stat.setInt(5, tran.harga);
             this.stat.setInt(6, tran.qty);
             this.stat.setInt(7, tran.total_bayar);
             this.stat.setInt(8, Integer.parseInt(fid_transaksi.getText()));
             this.stat.executeUpdate();
             refreshTabel();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_bupdateActionPerformed

    private void fid_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fid_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fid_transaksiActionPerformed

    private void binputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binputActionPerformed
        try {
            penjualan tran = new penjualan();
            ftotal.setText(""+tran.total_bayar);
            this.stat = cn.prepareStatement("insert into transaksi values(?,?,?,?,?,?,?,?)");
            this.stat.setInt(1, 0);
            this.stat.setString(2, tran.nama_pelanggan);
            this.stat.setInt(3, tran.id_produk);
            this.stat.setString(4, tran.tanggal);
            this.stat.setString(5, tran.nama_produk);
            this.stat.setInt(6, tran.harga);
            this.stat.setInt(7, tran.qty);
            this.stat.setInt(8, tran.total_bayar);
            int pilihan= JOptionPane.showConfirmDialog(null, 
                    "Tanggal: "+tran.tanggal+"\nNama Pelanggan: "
                    +tran.nama_pelanggan+"\nPembelian: "+tran.qty+""+tran.nama_produk+
                    "\nTotal bayar: "+tran.total_bayar+"\n","Tambahkan Transaksi?", 
                    JOptionPane.YES_NO_OPTION);
            if(pilihan == JOptionPane.YES_OPTION){
                this.stat.executeUpdate();
                refreshTabel();
              
        }else if(pilihan == JOptionPane.NO_OPTION){
            
        }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_binputActionPerformed

    private void fid_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fid_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fid_produkActionPerformed

    private void ttransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttransaksiMouseClicked
       fid_transaksi.setText(model.getValueAt(ttransaksi.getSelectedRow(), 0).toString());
       fnama_pelanggan.setText(model.getValueAt(ttransaksi.getSelectedRow(), 1).toString());
        try {
            int srow = ttransaksi.getSelectedRow();
            Date date = new SimpleDateFormat("YYYY-MM-dd").parse((String)model.getValueAt(srow,3));
            ftanggal.setDate(date);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       fqty.setText(model.getValueAt(ttransaksi.getSelectedRow(), 6).toString());
       ftotal.setText(model.getValueAt(ttransaksi.getSelectedRow(), 7).toString());
       
       
    }//GEN-LAST:event_ttransaksiMouseClicked

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        try {
            penjualan tran = new penjualan();
            this.stat= cn.prepareStatement("delete from transaksi where id_transaksi=?");
            stat.setInt(1, Integer.parseInt(fid_transaksi.getText()));
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data berasil didelete");
            refreshTabel();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void bprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprodukActionPerformed
        produk pa =new produk();
        pa.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_bprodukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdelete;
    private javax.swing.JButton binput;
    private javax.swing.JButton bproduk;
    private javax.swing.JButton bupdate;
    private javax.swing.JComboBox<String> fid_produk;
    private javax.swing.JTextField fid_transaksi;
    private javax.swing.JTextField fnama_pelanggan;
    private javax.swing.JTextField fqty;
    private com.toedter.calendar.JDateChooser ftanggal;
    private javax.swing.JTextField ftotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable ttransaksi;
    // End of variables declaration//GEN-END:variables
}
